### ISSUE TITLE
希望有示例说明下怎么做到的

### ISSUE THREAD

**Issue by frkijh** [WhileKing/ea-router#5]
rt，我Pull下来添加了自己写的示例没法npm run dev，尝试几次都没法解决这个问题

**Comment by dydhyhwu** [comment]
这是个库，不是个vue项目噢。
在一个vue项目里安装这个依赖：
> npm instal --save ea-router
然后根据文档里的描述进行设置。

后续我会加入示例项目讲解一下

**Comment by frkijh** [comment]
你好老铁！我引入了vue-property-decorator并重写了下我的示例代码，现在能出现示例要的文本的，但是又有个小问题，defaultLayout的内容会重复显示
这是我的示例项目列表
![image](https://user-images.githubusercontent.com/59047022/121330116-583aaa00-c948-11eb-8c97-eaa9a35d31a4.png)
这是先点击了【我的工作台】-【选项1】再点击了【选项2】的效果，重复显示了defaultLayout
![image](https://user-images.githubusercontent.com/59047022/121330273-6f799780-c948-11eb-8eba-0d1503824089.png)
我看我的选项1、选项2里面都有已经定义的Layout模板，为什么还会有默认模板的显示？

**Comment by dydhyhwu** [comment]
section1, section2的父目录没有Layout喔，所以会使用默认模板，这个是正常的。

**Comment by frkijh** [comment]
谢谢老铁指点！您的方法对我的帮助很大！！！
