### ISSUE TITLE
添加了@Meta的标题，但使用面包屑打印meta时显示标题未定义

### ISSUE THREAD

**Issue by frkijh** [WhileKing/ea-router#6]
![image](https://user-images.githubusercontent.com/59047022/121459021-10b22d80-c9dd-11eb-99a5-1ea649cbeee3.png)
上面一个打印的是
![image](https://user-images.githubusercontent.com/59047022/121459062-24f62a80-c9dd-11eb-833a-6087eaa91edb.png)
下面一个出现Untit的打印的是meta.title，显示untitled
这是我路由的定义
![image](https://user-images.githubusercontent.com/59047022/121459156-50791500-c9dd-11eb-9d2d-b290549b627f.png)

**Comment by frkijh** [comment]
![image](https://user-images.githubusercontent.com/59047022/121481650-ebceb200-c9fe-11eb-9571-5b20aa6dd285.png)
但是我另一个导航栏获取route.meta.title可以显示
![image](https://user-images.githubusercontent.com/59047022/121481877-26384f00-c9ff-11eb-8e74-90b8bdb019d2.png)

**Comment by dydhyhwu** [comment]
看是不是因为在layout里引起的，晚上回去我试一试。这个属性我使用的频率不是很高

**Comment by dydhyhwu** [comment]
![image](https://user-images.githubusercontent.com/7239380/121649295-079f8a00-cacb-11eb-8b64-ec22927c0de0.png)
我这边好像没复现出来，你的目录能打包一份或者给个仓库地址我看一下么

**Comment by dydhyhwu** [comment]
![image](https://user-images.githubusercontent.com/7239380/121649505-36b5fb80-cacb-11eb-8129-b1b309e602ad.png)

**Comment by frkijh** [comment]
我还不太会用git，上手试试再发给你！谢谢老铁！


来自 魅族 16 X

-------- 原始邮件 --------
发件人：dydhyh ***@***.***>
时间：2021年6月11日 15:39
收件人：WhileKing/ea-router ***@***.***>
抄送：frkijh ***@***.***>,Author ***@***.***>
主题：Re: [WhileKing/ea-router] 添加了@Meta的标题，但使用面包屑打印meta时显示标题未定义 (#6)

**Comment by frkijh** [comment]
![image](https://user-images.githubusercontent.com/59047022/123590494-4cdaf000-d81d-11eb-9efd-02432db078a8.png)
我的仓库地址github-windows://openRepo/http://192.168.20.6:8001/r/web_xz_practice.git

**Comment by frkijh** [comment]
![image](https://user-images.githubusercontent.com/59047022/123591439-8c560c00-d81e-11eb-9bfb-60e5a03d359d.png)

我的仓库地址https://github.com/frkijh/vueTest.git
我用vue-devtools测试的时候也是如楼主一样有Meta的，但是打印$route.match中的就是空的

**Comment by frkijh** [comment]
准确的来说是src/compoments/vue-admin/BreadCrumb文件，打印部分在第29行。谢谢楼主了！

**Comment by frkijh** [comment]
老铁，我忽然明白为毛了！因为我前几个都没有设置Meta中的name信息。。。只有最后一个有
