### ISSUE TITLE
请问如何添加新路由？我想做个redirect到首页的操作

### ISSUE THREAD

**Issue by frkijh** [WhileKing/ea-router#7]
![QQ图片20210702133146](https://user-images.githubusercontent.com/59047022/124225350-e239f500-db39-11eb-9913-18189bfd08ff.jpg)
期待楼主能解惑！先谢谢了！

**Comment by frkijh** [comment]
https://github.com/frkijh/vueTest
上面是我的测试项目

**Comment by dydhyhwu** [comment]
目前暂时没支持redirect功能，不知道你是什么需求需要在路由定义的时候就做跳转。
因为这种跳转并不会触发导航守卫，而且在日常开发中也不建议使用redirect，如果是路由名称不合适，可以使用alias来处理。

如果你需要redirect的功能，可以提供另一种实现方式：
在你需要跳转的路由页面下（在这里就是 / 对应的路由，也就是目录下的`Layout.vue` 或者是 `Index.vue`），在mounted钩子里直接用`router`进行跳转

**Comment by frkijh** [comment]
谢谢老铁解惑，不过为什么不建议用redirect呢？我回头再看看Alias。

**Comment by dydhyhwu** [comment]
redirect是用来做重定向的， 看是否是你需要的场景。
在前端我目前碰到的还是比较少的，定义一个路由给用来做跳转，那这个路由的意义不大，不如直接去跳转后的路由。
重定向是不会触发导航守卫的，这也是一个弊病。

**Comment by frkijh** [comment]
太感谢老铁，你的解释很好！
